# Generated by Django 6.0.6 on 2026-06-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('vehicle_registration', models.CharField(max_length=20)),
                ('booking_date', models.DateField()),
                ('service_required', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
