# Generated by Django 6.0.6 on 2026-07-03 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_customer_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='garage.vehicle'),
        ),
    ]
